[project]
name = "ai-parliament"
version = "0.1.0"
description = "Projekt AI-Parliament"
authors = []
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"